name: set up timux and codex

on:
  workflow_dispatch:
  push:


jobs:
  setup:
    runs-on: ubuntu-latest
      
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install timux and other erquired softwares
        run: |
          sudo apt-get update
          sudo apt-get install -y tmux
          sudo apt-get install -y ripgrep
          sudo apt-get install -y ncurses-term

      - name: configure timux
        run: |
          cat > ~/.tmux.conf << EOF
          set-option -g history-limit 100000
          set -g mouse on
          EOF

      - name: install node js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install gemini
        env:
          GEMINI_CLI_TRUST_WORKSPACE: true
          GEMINI_MODEL: gemini-3-pro-preview
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_GEMINI_BASE_URL: https://app.dataannotation.tech/api/llm_proxy/gemini
        run: |
          npm install -g @google/gemini-cli
          git clone https://github.com/mmumshad/simple-webapp-flask.git my-qual-project
          cp -r my-qual-project my-qual-project-start
          tar -cf my-qual-project-start.tar my-qual-project-start
          echo "======================="
          python3 run_gemini.py
          sleep 70
          ls 
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add GEMINI.md
          git commit -m "CI: update metadata files [skip ci]" || echo "Nothing to commit"
          git push || echo "Push failed"
          echo "==================="
          cat my-qual-project-start-log.log
          echo "==================="
          echo "=== Active tmux sessions ==="
          tmux ls

      - name: prepare final artifacts
        run: |
          tar -czf my-qual-project-start-final.tar.gz my-qual-project-start
      - name: uploading artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qualifucation_results
          path: |
            my-qual-project-start-log.log
            my-qual-project-start.ta
            my-qual-project-start-final.tar.gz
            my-qual-project-start/
          retention-days: 30
